apiVersion: v1
kind: Service
metadata:
  name: web-hello-to-nginx
spec:
  type: LoadBalancer
  selector:
    app: web-hello-to-nginx
  ports:
  - port: 3030
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-hello-to-nginx
spec:
  replicas : 3
  selector:
    matchLabels:
      app: web-hello-to-nginx
  template:
    metadata:
      labels:
        app: web-hello-to-nginx
    spec:
      containers:
      - name: web-hello-to-nginx
        image: bstashchuk/k8s-web-to-nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
          
