apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-hello
spec:
  selector:
    matchLabels:
      app: java-hello
  template:
    metadata:
      labels:
        app: java-hello
    spec:
      containers:
      - name: java-hello
        image: in28min/hello-world-rest-api:0.0.1.RELEASE
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-hello
spec:
  selector:
    app: java-hello
  ports:
  - port: 8080
    targetPort: 8080

